#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.."
ENV_FILE=.env.gtm-demo

banner "Verify the YouTube tracker in a test GTM workspace"

stage "Open a dedicated web-container workspace"
open_url "https://tagmanager.google.com/"
step "Sign in and select a test web container. Keep npm run demo running in another terminal."
step "Copy its public GTM container ID from the workspace header. No credentials are collected."
ask GTM_DEMO_CONTAINER "Container ID, such as GTM-ABC123:"
if [[ ! "$GTM_DEMO_CONTAINER" =~ ^GTM-[A-Z0-9]+$ ]]; then
  warn "Expected a GTM container ID. Re-run with the ID shown in the workspace."
  exit 1
fi
write_env GTM_DEMO_CONTAINER "$GTM_DEMO_CONTAINER"

stage "Open the imported template and inspect permissions"
step "If already imported: click Templates in the workspace's left navigation, then the tracker under Tag Templates."
say "GTM keeps the imported copy. Repository updates do not change it; after a fix, use More Actions > Import in this editor and select the updated root template.tpl again."
step "Otherwise: Tag Templates > New > More Actions > Import. Select this repository's template.tpl."
step "In the Template Editor, click Permissions."
step "Permissions: read only for analytics_storage, ad_storage, ad_user_data, ad_personalization, functionality_storage, personalization_storage, security_storage; one exact jsDelivr URL; consentAwareYouTube execute only; template storage; debug-only logging."
pause "Press Enter after checking the permissions."

stage "Run the 12 imported tests inside GTM"
step "Stay in the Template Editor and click the Tests tab. The imported file already contains 12 tests; do not click Add Test."
step "Expand the first test and check that its first line is require('templateStorage').clear();. If missing, reimport the updated file before running tests."
step "The first test is 'Denied consent registers a watcher without loading'. The last is 'Activation permission stays independent and equivalent native policies reuse listeners'."
step "If the list is empty, stop and check that you imported the complete root template.tpl file, rather than pasting only its Code section."
step "Click the play-triangle Run Tests button to run all enabled tests. Ensure none of the 12 tests is disabled."
step "Read the results in the editor's Console panel. Expected: 12 tests run, all pass, zero failures."
say "These tests supply their own consent values and simulate loading. You do not need to play a video, click Grant analytics, run npm, or create a tag for this step."
step "If a test fails, expand its row using the arrow beside its name. Copy the failing test name and the full Console error."
say "To rerun only that test, hover over its row and click the play triangle that appears."
ask GTM_DEMO_TEST_RESULT "Record the test count and failures, or '12 passed, 0 failed':"
write_env GTM_DEMO_TEST_RESULT "$GTM_DEMO_TEST_RESULT"
confirm "Did GTM report all 12 tests passing with zero failures?" || exit 1

stage "Run the template code in the editor"
step "Click the Code tab in the same Template Editor. Leave the imported code unchanged."
step "Click Run Code and inspect the editor's Console panel for compilation, runtime, or permission errors. This is separate from Run Tests."
say "Use native mode with all six additional requirements, then each activation type. Also check explicit boolean variable selectors and empty native table-row validation. Follow docs/verification-issue-3.md. A play event is not expected in the editor."
say "Run Code may see unset consent as granted. Preview below must verify denied defaults and both consent transitions."
ask GTM_DEMO_EDITOR_RESULT "Record the Run Code outcome and any full Console error:"
write_env GTM_DEMO_EDITOR_RESULT "$GTM_DEMO_EDITOR_RESULT"
confirm "Did Run Code complete without compilation, runtime, or permission errors?" || exit 1
step "Save the imported template."
pause "Press Enter after saving."

stage "Configure the tracker tag"
step "Tags > New > Tag Configuration. Select the imported tracker template."
step "For the baseline walkthrough, choose GTM Consent Mode, no additional tracking requirements, and activation Not configured."
step "Trigger: DOM Ready, all pages. Add a Custom Event trigger named tracker_demo_repeat for the Repeat button."
step "Advanced Settings: Once per event; Consent Settings > Additional Consent Checks > No additional consent required."
step "Save the tag in this test workspace. The demo already queues consent defaults before the container snippet."
say "For a separate CMP test page, use the CMP consent template on Consent Initialization instead of competing defaults. See docs/developer-guide.md."
pause "Press Enter after saving the tag."

stage "Preview denied, granted, and withdrawn consent"
GTM_DEMO_URL="http://127.0.0.1:4173/?gtm=$GTM_DEMO_CONTAINER"
write_env GTM_DEMO_URL "$GTM_DEMO_URL"
step "In the workspace choose Preview, enter this demo URL, and connect:"
say "$GTM_DEMO_URL"
step "At the first tracker execution, Tag Assistant > Consent must show analytics_storage denied. The tag should have executed."
step "DevTools > Network: record the existing iframe baseline. Before grant, the tracker must add no companion or IFrame API request. Inspect cookies separately."
step "Play the video, click Grant analytics, and verify the pinned companion, API readiness, and custom_video play event."
step "Click Withdraw analytics; events must stop while video playback continues. Regrant must report the current position."
step "Click Execute template again. It must not create duplicate player work or play events."
ask GTM_DEMO_PREVIEW_RESULT "Record the consent, permissions, requests, cookies, and playback observations:"
write_env GTM_DEMO_PREVIEW_RESULT "$GTM_DEMO_PREVIEW_RESULT"
confirm "Did the denied, grant, withdrawal, regrant, and repeat checks pass?" || exit 1

stage "Verify saved grants and the ordinary YouTube host"
step "Reconnect Preview with these URL parameters, then repeat playback and withdrawal:"
say "$GTM_DEMO_URL&consent=granted&host=youtube.com"
step "Complete the issue #3 matrix in docs/verification-issue-3.md before recording the new modes as verified."
step "Native: add ad_storage and ad_user_data, reload with denied defaults, and grant each separately. Only the complete grant may start tracking; withdrawing any requirement must stop it."
step "Explicit: select GTM variables for tracker_analytics and tracker_youtube, and add tracker_demo_consent as a Custom Event trigger with no grant-only filter. Keep Once per event."
say "$GTM_DEMO_URL&mode=explicit"
step "Verify initial consent-update execution before DOM Ready, later page-trigger reuse, grant, withdrawal, regrant, Repeat, invalid variable values, and saved consent using &consent=granted."
step "Use network throttling for withdrawal during loading, and verify activation permission independently as described in the matrix."
step "Also test your CMP's saved choices and defaults on a separate CMP-owned page."
step "Record browser details and failures. Keep network errors distinct from tracker failures."
ask GTM_DEMO_FINAL_RESULT "Record the saved-grant, host, and CMP-defaults results, including pending checks:"
write_env GTM_DEMO_FINAL_RESULT "$GTM_DEMO_FINAL_RESULT"
say "Results are in ignored .env.gtm-demo. Share the non-sensitive observations with the maintainer for review."
say "This wizard does not publish the container or submit a Gallery release."
finish
